# Generated by Django 5.2.11 on 2026-05-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('peso_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ufc.categoriapeso')),
            ],
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, help_text='Ex: KO, TK, SUBMISSION, SPLIT DECISION, UNANIMOUS DECISION, NC, DQ', max_length=50, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ufc.categoriapeso')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ufc.evento')),
                ('lutador_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lutador_1', to='ufc.lutador')),
                ('lutador_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lutador_2', to='ufc.lutador')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencedor', to='ufc.lutador')),
            ],
        ),
    ]
