# Generated by Django 5.2.11 on 2026-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0002_alter_lutador_cadastrado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cadastrado_em',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cadastrado_por',
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
